util: fix parse_valid_date; util, policy: improve test coverage
EFForg/starttls-policy-cli pull request #11
Opened 2018-10-30 10:29 UTC by Snawoot

Changes:
* Fixes `util.parse_valid_date`: before it was returning TZ-unaware result depending on local timezone.
* Allows config merge between subclasses of MergableConfig.
* Adds test utility function for portable `assertRaisesRegex` assertion.
* Improves test coverage: now only two lines in main file are not covered by tests.

2018-10-30 18:45 UTC, Snawoot commented
Gonna rebase, please standby

2018-10-30 18:48 UTC, Snawoot commented
Updated

2018-11-01 22:07 UTC, sydneyli requested changes
Thanks for the cleanup, @Snawoot! These changes look good to me. One last thing-- now that the coverage is improved, let's bump up the `--fail-under` in `tox.ini`!

2018-11-01 22:20 UTC, Snawoot commented
@sydneyli Done!

2018-11-01 22:33 UTC, sydneyli approved these changes
Thanks!

2018-11-01 22:33 UTC, merged